apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tech-test
  labels:
    app: devops-tech-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-tech-test
  template:
    metadata:
      labels:
        app: devops-tech-test
    spec:
      containers:
      - name: devops-tech-test
        image: {{ .Values.image | quote }}
        ports:
        - containerPort: '9002'
        env:
        - name: APP_PORT
          value: '9002'
        - name: GOOGLE_KEY
          value: {{ (fromJson .Values.secretJson).GOOGLE_KEY | quote }}
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ecr-registry-secret
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
