apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tech-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-tech-test
  template:
    metadata:
      labels:
        app: devops-tech-test
    spec:
      containers:
      - name: devops-tech-test
        image: 036676155227.dkr.ecr.eu-north-1.amazonaws.com/devops-tech-test:latest
        ports:
        - containerPort: 9002
        env:
        - name: APP_PORT
          value: "9002"
        - name: GOOGLE_KEY
          valueFrom:
            secretKeyRef:
              name: devops-tech-test-secret
              key: GOOGLE_KEY
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ecr-registry-secret