name: CI Pipeline
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy-scan.yml

  publish:
    needs: trivy-scan
    uses: ./.github/workflows/publish.yml