name: CI Pipeline
on:
  push:
    branches:
      - main
      - features/*

jobs:
  trivy:
    uses: crisselle-c/devops-tech-test/.github/workflows/trivy-scan.yml

  publish:
    needs: trivy
    uses: crisselle-c/devops-tech-test/.github/workflows/publish.yml