name: CI Pipeline
on:
  push:
    branches:
      - main
      - features/*

jobs:
  trivy-scan:
    uses: crisselle-c/devops-tech-test/.github/workflows/trivy-scan.yml@feature/devtechtest

  publish:
    needs: trivy
    uses: ./.github/workflows/publish.yml