name: CI Pipeline
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  scan:
    uses: ./.github/workflows/trivy-scan.yml

  publish:
    needs: scan
    uses: ./.github/workflows/publish.yml
    secrets: inherit
  
  deploy:
    needs: publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit