name: CI Pipeline
on:
  push:
    branches:
      - main
      - feature/*


jobs:
  build-and-publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  security-scan:
    needs: publish
    uses: ./.github/workflows/trivy-scan.yml
    secrets: inherit

  deployment:
    name: Deployment
    needs: scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
