name: CI Pipeline
on:
  push:
    branches:
      - main
      - feature/*


jobs:
  publish:
    name: Build and Publish
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  scan:
    name: Trivy Scan
    needs: publish
    uses: ./.github/workflows/trivy-scan.yml
    secrets: inherit

  deploy:
    name: Deployment
    needs: scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
