name: CI Pipeline
on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  security-scan:
    needs: build-and-publish
    uses: ./.github/workflows/trivy-scan.yml
    secrets: inherit

  codeql-scan:
    needs: build-and-publish
    uses: ./.github/workflows/codeql.yml
    secrets: inherit

  deployment:
    needs: security-scan
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
