name: Deploy to EKS

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION_CI:
        required: true
      AWS_SECRET_NAME:
        required: true

env:
  TERRAFORM_WORKING_DIR: ./terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_CI }}

    - name: Fetch AWS secrets and export env vars
      id: fetch_aws_secrets
      run: |
        secret_json=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_NAME }} --query SecretString --output text)
        echo "$secret_json" | jq -r 'to_entries|map("\(.key)=\(.value|@sh)")|.[]' >> $GITHUB_ENV
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION_CI }}


    - name: Kustomize build and apply
      run: |
        kubectl apply -k overlays/production
      env:
        KUBECONFIG: $HOME/.kube/config

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Terraform Init
      working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      run: terraform init

    - name: Terraform Apply
      working-directory: ${{ env.TERRAFORM_WORKING_DIR }}
      run: terraform apply -auto-approve
      env:
        TF_VAR_aws_region: ${{ secrets.AWS_REGION_CI }}
        TF_VAR_cluster_name: ${{ secrets.EKS_CLUSTER_NAME }}