name: Deploy to Kubernetes

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION_CI:
        required: true
      AWS_SECRET_NAME:
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_CI }}
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Retrieve secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          secret_json=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_NAME }} --query SecretString --output text)
          echo "GOOGLE_KEY=$(echo "$secret_json" | jq -r '.google_key')" >> $GITHUB_OUTPUT
          echo "KUBE_CONFIG=$(echo "$secret_json" | jq -r '.kube_config')" >> $GITHUB_OUTPUT

      - name: Setup kubeconfig file
        run: |
          echo "${{ steps.get-secrets.outputs.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        env:
          KUBE_CONFIG: ${{ steps.get-secrets.outputs.KUBE_CONFIG }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Verify kubectl config
        run: kubectl config get-contexts

      - name: Create Kubernetes secret
        env:
          GOOGLE_KEY: ${{ steps.get-secrets.outputs.GOOGLE_KEY }}
        run: |
          kubectl create secret generic ${GITHUB_REPOSITORY#*/} \
            --from-literal=GOOGLE_KEY=$GOOGLE_KEY \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy using Kustomize
        run: |
          kubectl apply -k kustomize/overlays/production

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/${GITHUB_REPOSITORY#*/} -n default
