on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION_CI:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure temporary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_CI }}

      - name: Create and Access ECR Repo (if not exists)
        env:
          AWS_REGION_CI: ${{ secrets.AWS_REGION_CI }}
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          aws ecr describe-repositories --repository-names $REPO_NAME >/dev/null 2>&1 || \
          (aws ecr create-repository --repository-name $REPO_NAME && echo "Created ECR repo: $REPO_NAME") || \
          echo "ECR repo $REPO_NAME already exists or failed to create, continuing..."

          # Get Aws Account ID and Login
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          
          aws ecr get-login-password --region $AWS_REGION_CI | \
            docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION_CI.amazonaws.com

      - name: Build and Push Docker Image
        env:
          AWS_REGION_CI: ${{ secrets.AWS_REGION_CI }}
          ACCOUNT_ID: ${{ env.ACCOUNT_ID }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            IMAGE_TAG="latest"
            DOCKER="Dockerfile"
          else
            IMAGE_TAG="${BRANCH_NAME//\//-}"
            DOCKER="Dockerfile.dev"
          fi

          # Build and push image
          IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION_CI.amazonaws.com/${GITHUB_REPOSITORY#*/}:$IMAGE_TAG
          echo "Building and pushing $IMAGE_URI"

          docker build -t "$IMAGE_URI" -f app/$DOCKER app/
          docker push "$IMAGE_URI"