# on:
#   workflow_call:

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo "${{ github.repository }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')
          docker build --no-cache -t "$IMAGE_TAG:latest" -f app/Dockerfile app/

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.63.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.63.0_Linux-64bit.deb
          rm trivy_0.63.0_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        run: |
          IMAGE_TAG=$(echo "${{ github.repository }}" | awk -F/ '{print $2}' | tr '[:upper:]' '[:lower:]')
          trivy image --exit-code 1 --severity HIGH,CRITICAL "$IMAGE_TAG:latest"