resources:
  - ../../base

patchesStrategicMerge:
  - patch-env.yml

secretGenerator:
  - name: devops-tech-test-secret
    literals:
      - GOOGLE_KEY=${GOOGLE_KEY}
      - APP_PORT=${APP_PORT}
generatorOptions:
  disableNameSuffixHash: true